ci: fix test

diff --git a/.github/workflows/check.yaml b/.github/workflows/check.yaml
--- a/.github/workflows/check.yaml
+++ b/.github/workflows/check.yaml
@@ -30,30 +30,16 @@ jobs:
       - name: Test installed files
         run: |
           set -exo pipefail
-          if [[ -f "$HOME/.gitignore_global" && "$HOME/.gitignore_global" == *"${{ github.workspace }}/.gitignore_global"* ]]; then
-            echo ".gitignore_global is correctly linked"
-          else
-            echo ".gitignore_global is missing or not linked correctly" && exit 1
+          if find "$HOME/.gitignore" -type f -maxdepth 1; then
+            echo "[x] TEST FAILED. .gitignore found."
+            exit 1
           fi
 
+          ls -la "$HOME" | grep .gitignore_global | grep "${{ github.workspace }}/.gitignore_global"
           if [[ "${{ matrix.force }}" == "n" ]]; then
-            if [[ ! -f "$HOME/.docker/config.json" || "$HOME/.docker/config.json" == *"${{ github.workspace }}/HOME/.docker/config.json"* ]]; then
-              echo "config.json is correctly excluded"
-            else
-              echo "config.json is incorrectly linked" && exit 1
-            fi
-          else
-            if [[ -f "$HOME/.docker/config.json" && "$HOME/.docker/config.json" == *"${{ github.workspace }}/HOME/.docker/config.json"* ]]; then
-              echo "config.json is correctly linked"
-            else
-              echo "config.json is missing or not linked correctly" && exit 1
-            fi
+            docker_grep_arg="-v"
           fi
-
-          for file in profile_dotfiles_init_aws.sh profile_dotfiles_init_kubectl.sh profile_dotfiles_init_kubectx.sh; do
-            if [[ -f "/etc/profile.d/$file" ]]; then
-              echo "$file exists"
-            else
-              echo "$file is missing" && exit 1
-            fi
-          done
+          ls -la "$HOME/.docker" | grep config.json | grep ${docker_grep_arg} "${{ github.workspace }}/HOME/.docker/config.json"
+          ls -la "/etc/profile.d" | grep profile_dotfiles_init_aws.sh
+          ls -la "/etc/profile.d" | grep profile_dotfiles_init_kubectl.sh
+          ls -la "/etc/profile.d" | grep profile_dotfiles_init_kubectx.sh
